- name: Initialize kubernetes control plane on master
  hosts: tag_Name_easypay-master
  become: true
  gather_facts: yes
  tasks:
    - name: Initialize kubeadm control plane
      shell: |
        sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}
      args:
        creates: /etc/kubernetes/admin.conf
      register: kube_init
    - name: Create .kube dir
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        mode: 0755
    - name: Copy admin.conf to ubuntu kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        mode: 0644
    - name: Install Flannel CNI (delegate to master)
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Save join command to /tmp/join_cmd.sh
      shell: kubeadm token create --print-join-command > /tmp/join_cmd.sh
      args:
        creates: /tmp/join_cmd.sh

- name: Join workers to cluster
  hosts: tag_Name_easypay-worker-1:tag_Name_easypay-worker-2:tag_Name_easypay-worker-3
  become: true
  gather_facts: yes
  tasks:
    - name: Pull join command from master
      delegate_to: "{{ groups['tag_Name_easypay-master'][0] }}"
      fetch:
        src: /tmp/join_cmd.sh
        dest: /tmp/join_cmd.sh
        flat: yes
      run_once: true

    - name: Make join script executable
      file:
        path: /tmp/join_cmd.sh
        mode: '0755'

    - name: Join node to cluster
      shell: bash /tmp/join_cmd.sh
      args:
        warn: no
      when: "'node-role.kubernetes.io/master' not in ansible_facts['ec2_metadata']['instance_type'] | default('')"
